version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: blog_mysql_db
    volumes:
      - ./api/docker/db/init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: blog_development
      MYSQL_USER: blog_admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
  api:
    build: ./api
    container_name: blog_api
    tty: true
    stdin_open: true
    volumes:
      - ./api:/blog/api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_USER: blog_admin
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: mysql
  frontend:
    build: ./frontend
    container_name: blog_frontend
    volumes:
      - ./frontend:/blog/frontend
      - /blog/frontend/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api